runCDPipeline(application: env.APP_NAME,
              agent: "maven",
              compileCommands: "mvn package -DskipTests",
              testCommands: "mvn test",
              artifactsDir: "./target")