pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    environment {
        APP_TEMPLATE_FILE = "openshift/template.yaml"
        APP_CONFIG_FILE = "environments/prod/config.yaml"
        APP_DEPLOYMENT_PATCH_FILE = "environments/prod/deployment.yaml"
    }
    stages {
        stage("Initialize") {
            steps {
                library(identifier: 'openshift-pipeline-library@master', 
                        retriever: modernSCM([$class: 'GitSCMSource', 
                                             credentialsId: env.REPOSITORY_CREDENTIALS, 
                                             remote: env.PIPELINE_LIBRARY_REPOSITORY]))
                
                script {
                    env.PROJECT = getProject()
                }
            }
        }
        stage("Select Image") {
            steps { 
                script {
                    env.TAG = selectTag(project: env.SRC_PROJECT, image: env.IMAGE_NAME)
                }
            }
        }
        stage("Promote Image") {
            steps {
                withDockerRegistry([credentialsId: env.SRC_REGISTRY_CREDENTIALS, url: "http://${SRC_REGISTRY_URL}"]) {
                    withDockerRegistry([credentialsId: env.DST_REGISTRY_CREDENTIALS, url: "http://${DST_REGISTRY_URL}"]) {
                        script {
                            openshift.withCluster {
                                openshift.raw("image mirror --insecure ${SRC_REGISTRY_URL}/${SRC_PROJECT}/${IMAGE_NAME}:${TAG} ${DST_REGISTRY_URL}/${DST_PROJECT}/${IMAGE_NAME}:${TAG}")
                            }
                        }
                    }
                }   
            }
        }
        stage ("Apply Template") {
            steps {
                gitClone(repository: env.GIT_REPO, branch: env.TAG, credentialsId: env.REPOSITORY_CREDENTIALS)
                
                applyTemplate(clusterUrl: env.DST_CLUSTER_URL, 
                              clusterToken: env.DST_CLUSTER_TOKEN,
                              project: env.DST_PROJECT, 
                              template: env.APP_TEMPLATE_FILE, 
                              application: env.APP_NAME, 
                              image: env.IMAGE_NAME, 
                              createBuildObjects: false)
            }  
        }
        stage ("Apply Configuration") {
            steps {
                dir("config") {
                    gitClone(repository: env.GIT_REPO_CONFIG, branch: env.TAG, credentialsId: env.REPOSITORY_CREDENTIALS)

                    applyConfiguration(clusterUrl: env.DST_CLUSTER_URL, 
                                    clusterToken: env.DST_CLUSTER_TOKEN,
                                    project: env.DST_PROJECT, 
                                    application: env.APP_NAME, 
                                    config: env.APP_CONFIG_FILE, 
                                    deploymentPatch: env.APP_DEPLOYMENT_PATCH_FILE)
                }
            }
        }   
        stage("Approve Deploy") {
            when {
                expression {
                    return env.PROD_APPROVAL_GROUP
                }
            }
            steps {
                processApproval(env.PROD_APPROVAL_GROUP)
            }
        }
        stage("Deploy Image") {
            steps {
                deployImage(clusterUrl: env.DST_CLUSTER_URL, 
                            clusterToken: env.DST_CLUSTER_TOKEN,
                            project: env.DST_PROJECT, 
                            application: env.APP_NAME, 
                            image: env.IMAGE_NAME, 
                            tag: env.TAG)
            }
        }
    }
}