@Library("pipeline-library") 
import com.redhat.openshift.pipelines.Commons

def commons = new com.redhat.openshift.pipelines.Commons(this)

pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    environment {
        APP_CONFIG = "openshift/environments/${ENVIRONMENT}/config.yaml"
        APP_DEPLOYMENT_PATCH = "openshift/environments/${ENVIRONMENT}/deployment.yaml"
    }
    stages {
        stage("Initialize") {
            steps {
                script {
                    // Gets the application project
                    env.PROJECT = commons.getApplicationProject()      
                }
            }
        }
        stage("Checkout Code") {
            steps {
                script {
                    openshift.withCluster(env.DST_CLUSTER_URL, env.DST_CLUSTER_TOKEN) {
                        openshift.withProject(env.PROJECT) {
                            commons.gitCheckout(env.GIT_REPO, env.GIT_BRANCH, env.GIT_SECRET)
                        }
                    }
                }
            }
        }
        stage ("Apply Configuration") {
            when {
                expression {
                    return commons.hasConfig(env.APP_CONFIG) || commons.hasDeploymentPatch(env.APP_DEPLOYMENT_PATCH)  
                }
            }
            steps {
                script {
                    openshift.withCluster(env.DST_CLUSTER_URL, env.DST_CLUSTER_TOKEN) {
                        openshift.withProject(env.PROJECT) {
                            commons.applyConfigChanges(APP_CONFIG, APP_DEPLOYMENT_PATCH)
                        }
                    }
                }
            }
        }
        stage("Restart Application") {
            steps {
                script {
                    openshift.withCluster(env.DST_CLUSTER_URL, env.DST_CLUSTER_TOKEN) {
                        openshift.withProject(env.PROJECT) {
                            openshift.selector("dc/${env.APP_NAME}").rollout().latest()
                        } 
                    }
                }
            }
        }
    }
}