pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    environment {
        APP_CONFIG = "environments/prod/config.yaml"
        APP_DEPLOYMENT_PATCH = "environments/prod/deployment.yaml"
        PROJECT = getProject()
        CREDENTIALS = "${env.PROJECT}-${env.GIT_SECRET}"
    }
    stages {
        stage("Set Config Branch") {
            steps {
                script {
                    env.GIT_BRANCH = input(id: 'branch',
                                           message: 'Set branch',
                                           parameters: [string(defaultValue: '', name: 'branch')]);
                    
                    gitClone(repository: env.GIT_REPO, branch: env.GIT_BRANCH, credentialsId: env.CREDENTIALS)
                }
            }
        }
        stage ("Apply Configuration") {
            steps {
                applyConfiguration(clusterUrl: env.DST_CLUSTER_URL, 
                                   clusterToken: env.DST_CLUSTER_TOKEN, 
                                   project: env.DST_PROJECT, 
                                   application: env.APP_NAME, 
                                   config: env.APP_CONFIG, 
                                   deploymentPatch: env.APP_DEPLOYMENT_PATCH)
            }
        }   
        stage("Restart Application") {
            steps {
                restartApplication(clusterUrl: env.DST_CLUSTER_URL, 
                                   clusterToken: env.DST_CLUSTER_TOKEN, 
                                   project: env.DST_PROJECT, 
                                   application: env.APP_NAME)
            }
        }
    }
}