pipeline {
    agent {
        label "skopeo"
    }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    stages {
        stage("Initialize") {
            steps {
                script {
                    if (!env.APPROVAL_GROUP)
                        env.APPROVAL_GROUP = "prod-approvers"

                    if (!env.IMAGE_NAME)
                        env.IMAGE_NAME = env.APP_NAME
                }
            }
        }
        // If project environment variable is not set, asks for it
        stage("Set Project (Src)") {
            when {
                not {
                    expression {
                        return env.SRC_PROJECT_NAME
                    }
                }
            }
            steps {
                script {
                     env.SRC_PROJECT_NAME = input(id: 'project',
                                            message: 'Select the project where the tag to deploy resides',
                                            parameters: [string(defaultValue: '', name: 'Source Project')]);
                }
            }
        }
        stage("Set Project (Dst)") {
            when {
                not {
                    expression {
                        return env.DST_PROJECT_NAME
                    }
                }
            }
            steps {
                script {
                     env.DST_PROJECT_NAME = input(id: 'project',
                                            message: 'Select the project to deploy',
                                            parameters: [string(defaultValue: '', name: 'Destination Project')]);
                }
            }
        }
        // If application environment variable is not set, asks for it
        stage("Set Application") {
            when {
                not {
                    expression {
                        return env.APP_NAME
                    }
                }
            }
            steps {
                script {
                     env.APP_NAME = input(id: 'application',
                                    message: 'Select the application to deploy',
                                    parameters: [string(defaultValue: '', name: 'Application')]);
                }
            }
        }
        stage("Promote Objects") {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            // Uses the template from development project to generate the application in test
                            objects = openshift.process("${env.SRC_PROJECT_NAME}//${env.APP_TEMPLATE_NAME}", "-p", "PARAM_APP_NAME=${env.APP_NAME}");
/*
                            openshift.withCluster(env.DST_CLUSTER, env.DST_CLUSTER_TOKEN) {
                                openshift.withProject(env.DST_PROJECT_NAME) {
                                    for (o in objects) {
                                        // Prevents to promote the BuildConfig and ImageSream, the build is only done in development stages
                                        if (o.kind != "BuildConfig" && o.kind != "ImageStream") 
                                            openshift.apply(o);
                                    }
                                }
                            }
                            */
                        }
                    }
                }
            }
        }
        stage("Select Tag") {
            when {
                not {
                    expression {
                        return env.TAG
                    }
                }
            }
            steps {
                script {
                    openshift.withCluster() {
                        echo openshift.cluster();
                        openshift.withProject(env.SRC_PROJECT_NAME) {
                            // Generates a list of tags to deploy
                            def is = openshift.selector("is", env.APP_NAME).object();
                            def tags = "";
                            
                            for (tag in is.spec.tags)
                                tags = tag.name + "\n" + tags; 
                            
                            env.TAG = input(message: "Select version",
                                            parameters: [choice(choices: tags, description: 'Select a tag to deploy', name: 'Versions')]);
                        }
                    }
                }
            }
        }
        stage("Promote Tag") {
            steps {
                script {
                    sh "skopeo -h"
                }
            }
        }
        stage("Approve Deploy") {
            steps {
                script {
                    def submitter = input message: 'Confirm deployment', submitterParameter: 'submitter';
                    def user = submitter.substring(0, submitter.lastIndexOf("-"));
                    def canApprove = false;

                    openshift.withCluster() {
                        echo openshift.cluster();
                        openshift.verbose();
                        def groups = openshift.selector("groups").objects();

                        for (g in groups) {
                            if (g.metadata.name.equals(env.APPROVAL_GROUP) && g.users.contains(user)) {
                                canApprove = true;
                                echo "User ${user} from group ${g.metadata.name} approved the deployment"
                            } 
                        }

                        if (canApprove == false)
                            error "User ${user} is not allowed to approve the deployment"
                    }
                }
            }
        }
        stage("Deploy Application") {
            steps {
                script {
                    openshift.withCluster(env.DST_CLUSTER, env.DST_CLUSTER_TOKEN) {
                        openshift.withProject(env.DST_PROJECT_NAME) {
                            // Adds a trigger for deploying the tag, this will cause an automatic rollout
                            openshift.set("triggers", "dc/${env.APP_NAME}", "--from-image=${env.IMAGE_NAME}:${env.TAG}", "-c ${env.APP_NAME}");
                        } 
                    }
                }
            }
        }
    }
}