pipeline {
    agent {
        label "skopeo"
    }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    stages {
        stage("Initialize") {
            steps {
                script {
                    sh "skopeo -h"
                }
            }
        }
    }
}