runCDPipeline(application: env.APP_NAME,
              agent: "",
              compileCommands: "",
              testCommands: "",
              artifactsDir: "",
              integrationTestAgent: "",
              integrationTestCommands: "")