def commons = new com.redhat.openshift.pipelines.Commons(this)

pipeline {
    agent {
        label env.JENKINS_AGENT
    }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    environment {
        APP_TEMPLATE = "openshift/template.yaml"
    }
    stages {
        stage("Initialize") {
            steps {
                script {
                    env.TAG = "latest"
                    env.PROJECT = getProject()    
                    env.CREDENTIALS = "${env.PROJECT}-${env.GIT_SECRET}"
                }
            }
        }
        stage("Set Branch") {
            when {
                not {
                    expression {
                        return env.GIT_BRANCH
                    }
                }         
            }
            steps {
                script {
                    env.GIT_BRANCH = input(id: 'branch',
                                           message: 'Select branch',
                                           parameters: [string(name: 'Branch')]);
                }
            }
        }
        stage("Clone Code") {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(env.PROJECT) {
                            gitClone(repository: env.GIT_REPO, branch: env.GIT_BRANCH, credentialsId: env.CREDENTIALS)
                        }
                    }
                }
            }
        }
        stage ("Apply Template") {
            when {
                expression {
                    return utils.hasTemplate(env.APP_TEMPLATE)
                }
            }
            steps {
                applyTemplate(template: env.APP_TEMPLATE, application: env.APP_NAME, image: env.IMAGE_NAME)
            }
        }
        stage("Compile Code") {
            when {
                not {
                    expression {
                        return env.COMPILE_COMMAND.equals("none")
                    }
                }  
            }
            steps {
                sh env.COMPILE_COMMAND
            }
        }
        stage("Test Code") {
            when {
                not {
                    expression {
                        return env.TEST_COMMAND.equals("none")
                    }
                } 
            }
            steps {
                sh env.TEST_COMMAND
            }
        }
        stage("Analize Code") {
            when {
                not {
                    expression {
                        return env.CODE_ANALYSIS_COMMAND.equals("none")
                    }
                } 
            }
            steps {
                sh env.CODE_ANALYSIS_COMMAND
            }
        }
        stage("Release Artifacts") {
            when {
                not {
                    expression {
                        return env.RELEASE_COMMAND.equals("none")
                    }
                }        
            }
            steps {
                sh env.RELEASE_COMMAND
            }
        }
        stage("Build Image") {
            steps {
                buildImage(project: env.PROJECT, application: env.APP_NAME, image: env.IMAGE_NAME, artifactsDir: env.ARTIFACTS_DIR)
            }
        }
        stage("Tag Image") {
            when {
                expression {
                    return env.TAG_VERSION.equals("true")
                }   
            }
            steps {
                tagImage(project: env.PROJECT, srcImage: env.IMAGE_NAME, dstImage: env.IMAGE_NAME, dstTag: utils.getTag(env.TECH))
            }
        }
        stage("Deploy Image") {
            steps {
                deployImage(project: env.PROJECT, application: env.APP_NAME, image: env.IMAGE_NAME, tag: utils.getTag(env.TECH))
            }
        }
    }
}